// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQCZeblmw99xouW8eCX3OUbqW-LSW6Es',
    appId: '1:938718065620:web:1b264925db33d571385c41',
    messagingSenderId: '938718065620',
    projectId: 'app-movil-wati',
    authDomain: 'app-movil-wati.firebaseapp.com',
    storageBucket: 'app-movil-wati.firebasestorage.app',
    measurementId: 'G-83C70YZQR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPqbFh7eH70FOutHx6uH0WtibSFUa8xw',
    appId: '1:938718065620:android:b072ff96f5e4eb6f385c41',
    messagingSenderId: '938718065620',
    projectId: 'app-movil-wati',
    storageBucket: 'app-movil-wati.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALczS0a68_F0lt-cDs22VZGORH3Ho56jE',
    appId: '1:938718065620:ios:6354f9ef6aab1f16385c41',
    messagingSenderId: '938718065620',
    projectId: 'app-movil-wati',
    storageBucket: 'app-movil-wati.firebasestorage.app',
    iosBundleId: 'com.example.appMovilWati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALczS0a68_F0lt-cDs22VZGORH3Ho56jE',
    appId: '1:938718065620:ios:6354f9ef6aab1f16385c41',
    messagingSenderId: '938718065620',
    projectId: 'app-movil-wati',
    storageBucket: 'app-movil-wati.firebasestorage.app',
    iosBundleId: 'com.example.appMovilWati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmQCZeblmw99xouW8eCX3OUbqW-LSW6Es',
    appId: '1:938718065620:web:fdd5d77450861601385c41',
    messagingSenderId: '938718065620',
    projectId: 'app-movil-wati',
    authDomain: 'app-movil-wati.firebaseapp.com',
    storageBucket: 'app-movil-wati.firebasestorage.app',
    measurementId: 'G-DCG25JJRCM',
  );
}
